### PR TITLE
PR for Issue 138

### PR DESCRIPTION
**Pull request by liz-lawrens**

### CODE REVIEW

**Comment by jhou5** [comment]
For this feature, we should not change any final dockerfile code. Pls. correct it.

**Comment by liz-lawrens** [comment]
Updated changes. Please check and verify if OK.

**Comment by jhou5** [comment]
There is no such a parameter "--enable-libogg" in ffmpeg config, you may refer to this: https://github.com/FFmpeg/FFmpeg/blob/master/configure

**Comment by 1480c1** [comment]
Please do `git rebase upstream/master` on your local git branch to clean up all of the merge commits etc

**Comment by liz-lawrens** [comment]
Updated m4 files for Xeon

**Pull request closed without merging**
