### PR TITLE
Update ffmpeg to support more use cases and devices (XEON and XEONE3)

### PR DESCRIPTION
**Pull request by linxie47**
Fixed the compile issue and rebased to the latest version.

### CODE REVIEW

**Comment by linxie47** [comment]
/mnt/ffmpeg_svt_hevc.sh: line 4:     8 Segmentation fault      (core dumped) ffmpeg -f rawvideo -vcodec rawvideo -s 320x240 -r 30 -pix_fmt yuv420p -i test.yuv -c:v libsvt_hevc -y test.mp4
 6/10 Test  #6: test_xeon_ffmpeg_ubuntu1604_ffmpeg_svt_hevc ...***Failed    3.70 sec

The failure cannot be reproduced on my local machine. 
In addition, this PR doesn't contain any changes for xeon_ffmpeg_ubuntu1604.

**Comment by dpatel257** [comment]
Testing locally, Will update when have results.

**Comment by dpatel257** [comment]
Re-ran xeon/ubuntu1604 again on Travis. Passed gracefully. Might have been a glitch earlier.

Although the build fails on XeonE3/Centos75/ffmpeg+gst+dev package with following:

Step 74/168 : RUN yum copr enable -y arturh/intel-opencl
 ---> Using cache
 ---> e9d319a46c24
Step 75/168 : RUN yum install -y -q intel-opencl
 ---> Running in d3862948e689
Error: Nothing to do
The command '/bin/sh -c yum install -y -q intel-opencl' returned a non-zero code: 1

**Comment by linxie47** [comment]
> Re-ran xeon/ubuntu1604 again on Travis. Passed gracefully. Might have been a glitch earlier.
> 
> Although the build fails on XeonE3/Centos75/ffmpeg+gst+dev package with following:
> 
> Step 74/168 : RUN yum copr enable -y arturh/intel-opencl
> ---> Using cache
> ---> e9d319a46c24
> Step 75/168 : RUN yum install -y -q intel-opencl
> ---> Running in d3862948e689
> Error: Nothing to do
> The command '/bin/sh -c yum install -y -q intel-opencl' returned a non-zero code: 1

Thanks! I occassionaly meet the same issue. I think it may be caused by networking.

**Comment by linxie47** [comment]
@dpatel257 Any update for this PR?

**Comment by dpatel257** [comment]
@linxie47 I am still seeing yum error for the intel-opencl package on dev packages. 
I checked on two E3s we have here in the lab, I see it on both machines. Looks more than just a networking error.

**Comment by linxie47** [comment]
> @linxie47 I am still seeing yum error for the intel-opencl package on dev packages.
> I checked on two E3s we have here in the lab, I see it on both machines. Looks more than just a networking error.

Hi @dpatel257 
I met same issue on my local CentOS machine too, **NOT** inside docker.
$ sudo yum copr enable arturh/intel-opencl
Error: [Errno 14] curl#7 - "Failed connect to copr.fedoraproject.org:443; Operation now in progress"

I think there is something wrong with this repo **arturh/intel-opencl**. 
Could you try the same way and double check? Thanks.

**Comment by dpatel257** [comment]
sudo yum copr enable arturh/intel-opencl
Works fine for me but "yum install -y -q intel-opencl" fails for me.
Merging it now since you mention it passes for you.

**Pull request merged**
