### PR TITLE
support QAT images

### PR DESCRIPTION
**Pull request by xwu2git**

### CODE REVIEW

**Review by jhou5 — COMMENTED** [review]
found some error when building ubuntu2004 image

/home/vcse/ovc/test_pr/Dockerfiles/QAT/ubuntu-20.04/media/nginx/Dockerfile.m4:16: error: unsupported OS: ON
Sending build context to Docker daemon  12.64MB
Step 1/3 : FROM ON:openvisualcloud AS build
invalid reference format: repository name must be lowercase
make[2]: *** [QAT/ubuntu-20.04/media/nginx/CMakeFiles/build_qat_media_nginx_ubuntu2004] Error 1
make[1]: *** [QAT/ubuntu-20.04/media/nginx/CMakeFiles/build_qat_media_nginx_ubuntu2004.dir/all] Error 2
make: *** [all] Error 2

**Comment by xwu2git** [comment]
Fixed and upgraded versions.

**Comment by jhou5** [comment]
@xwu2git have any oppotunity to look at below build error? It looks parameters OS_NAME and OS_VERSION are not set correct. For existing images, I am using CMakefiles under OS directory to define it. Can you pls. share what ways you are using for this one.
**https://github.com/OpenVisualCloud/Dockerfiles/blob/v2.0/Xeon/ubuntu-20.04/CMakeLists.txt
set(OS_NAME "ubuntu")
set(OS_VERSION "20.04")**

/home/vcse/ovc/test_pr/Dockerfiles/QAT/ubuntu-20.04/media/nginx/Dockerfile.m4:16: error: unsupported OS: ON
Sending build context to Docker daemon 12.64MB
Step 1/3 : FROM ON:openvisualcloud AS build
invalid reference format: repository name must be lowercase
make[2]: *** [QAT/ubuntu-20.04/media/nginx/CMakeFiles/build_qat_media_nginx_ubuntu2004] Error 1
make[1]: *** [QAT/ubuntu-20.04/media/nginx/CMakeFiles/build_qat_media_nginx_ubuntu2004.dir/all] Error 2
make: *** [all] Error 2

**Comment by xwu2git** [comment]
OS/Version updated.

**Pull request merged**
