### PR TITLE
SVT Version Upgrade -  SVT-AV1 to v0.7.0 and SVT-HEVC to v1.4.1

### PR DESCRIPTION
**Pull request by liz-lawrens**

### CODE REVIEW

**Comment by dpatel257** [comment]
Working except for GST-HEVC plugin would not load for HEVC 1.4.1
Fix is known by SVT team, Jun working on getting HEVC 1.4.2 with the fix

**Comment by jhou5** [comment]
can you pls. update SVT version info for the doc, too. https://github.com/OpenVisualCloud/Dockerfiles/tree/master/doc

**Comment by jhou5** [comment]
I mean gst.md and ffmpeg.md

**Comment by liz-lawrens** [comment]
Updated the docs with version info.

**Pull request merged**
