### PR TITLE
support the Intel QAT platform

### PR DESCRIPTION
**Pull request by xwu2git**
-dev, centos 7.4-7.5 not yet developed. Should be straightforward to add those.

### CODE REVIEW

**Comment by xwu2git** [comment]
@jhou5 strange error message: 
8/8 Test #8: test_xeon_nginx_rtmp_ubuntu1804_nginx_upload ......   Passed    8.61 sec
100% tests passed, 0 tests failed out of 8
Total Test time (real) = 101.24 sec
The command "travis_retry ctest -V" exited with 0.
Done. Your build exited with 1.

**Comment by jhou5** [comment]
When doing the test, found a strange thing, why ffmpeg command is comment out from nginx hevc config, so that no test is actually run:

- nginx_rtmp_hevc.sh
- nginx_dash_hevc.sh
- nginx_hls_hevc.sh

**Comment by xwu2git** [comment]
where is it commented out?

**Comment by jhou5** [comment]
Comment out is not from this PR. I would handle it seperately.

**Pull request merged**
