### PR TITLE
update to ffmpeg analytics v0.3

### PR DESCRIPTION
**Pull request by linxie47**
As ffmpeg analytics v0.3 released, we need update the changes to OVC/Dockerfiles too.

### CODE REVIEW

**Comment by jhou5** [comment]
@linxie47 it looks all anlytics-ffmpeg image test failed, can you check it? 
https://github.com/OpenVisualCloud/Dockerfiles/pull/240/checks?check_run_id=274427620

**Comment by linxie47** [comment]
> @linxie47 it looks all anlytics-ffmpeg image test failed, can you check it?
> https://github.com/OpenVisualCloud/Dockerfiles/pull/240/checks?check_run_id=274427620

Fixed. :)

**Comment by linxie47** [comment]
@jhou5 any update for this PR?

**Comment by jhou5** [comment]
Approved. Thanks!

**Pull request merged**
