### PR TITLE
Upgrade to OpenVINO 2020.2 and FFVA v0.5

### PR DESCRIPTION
**Pull request by linxie47**

### CODE REVIEW

**Comment by jhou5** [comment]
gst plugin build failed, maybe caused by imcompatibility of existing gst plugin and new openVINO. Would double check details.

**Comment by jhou5** [comment]
**Root Caused: env PKG_CONFIG_PATH should not be removed, which introduce the build failure:**
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Checking for module 'gstreamer-1.0>=1.14'
--   No package 'gstreamer-1.0' found
CMake Error at /usr/local/share/cmake-3.13/Modules/FindPkgConfig.cmake:452 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.13/Modules/FindPkgConfig.cmake:622 (_pkg_check_modules_internal)
  gst/common/CMakeLists.txt:12 (pkg_check_modules)

**Comment by linxie47** [comment]
> **Root Caused: env PKG_CONFIG_PATH should not be removed, which introduce the build failure:**
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1")
> -- Checking for module 'gstreamer-1.0>=1.14'
> -- No package 'gstreamer-1.0' found
> CMake Error at /usr/local/share/cmake-3.13/Modules/FindPkgConfig.cmake:452 (message):
> A required package was not found
> Call Stack (most recent call first):
> /usr/local/share/cmake-3.13/Modules/FindPkgConfig.cmake:622 (_pkg_check_modules_internal)
> gst/common/CMakeLists.txt:12 (pkg_check_modules)

Awesome!! @jhou5  I'll append a fix. :)

**Comment by jhou5** [comment]
The fix works. Thanks @linxie47 for the quick fix.

**Comment by jhou5** [comment]
There has another failure found in dev image, we are looking into it.

**Comment by jhou5** [comment]
@linxie47 can you update doc accordingly?

**Comment by linxie47** [comment]
> @linxie47 can you update doc accordingly?

sure. New PR for doc update. https://github.com/OpenVisualCloud/Dockerfiles/pull/460

**Comment by dpatel257** [comment]
> There has another failure found in dev image, we are looking into it.

Analytics Dev image on Ubuntu1604 has problems building model-optimizer:
https://github.com/opencv/dldt/issues/459

**Comment by linxie47** [comment]
> > There has another failure found in dev image, we are looking into it.
> 
> Analytics Dev image on Ubuntu1604 has problems building model-optimizer:
> [opencv/dldt#459](https://github.com/opencv/dldt/issues/459)

@dpatel257 Great!!!!! Thanks for the fix. :)

**Comment by jhou5** [comment]
It works. Thx!

**Pull request merged**
