### PR TITLE
updated to OpenCV v4.1.0 & fixed cmake build options

### PR DESCRIPTION
**Pull request by deathboydmi**
Hello, my name is Dmitry Smertn,
We needed to include support for the OpenCV G-API in our project. To do this, changed the version of OpenCV to the one used in OpenVINO R1 (OpenCV v4.1.0). Build OpenCV errors occurred when downloading additional frameworks that were fixed by adding options when installing cmake.
Please review my changes and add them to the source Dockerfile. No problems were found in the local build with changes.

Respectfully,
Dmitry Smertin

### CODE REVIEW

**Comment by jhou5** [comment]
@deathboydmi Thanks for the contribution and warmly welcome to OVC project. However from the CI build log, it shows build error, can you look at it?

One example of build failure is shown as below-
-- Using system-installed CURL
-- Using system-installed ZLIB
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:387 (message):
  CMAKE_USE_SYSTEM_ZLIB is ON but a zlib is not found!
Call Stack (most recent call first):
  CMakeLists.txt:685 (CMAKE_BUILD_UTILITIES)
-- Configuring incomplete, errors occurred!
See also "/home/cmake-3.13.1/CMakeFiles/CMakeOutput.log".
See also "/home/cmake-3.13.1/CMakeFiles/CMakeError.log".
---------------------------------------------
Error when bootstrapping CMake:
Problem while running initial CMake
---------------------------------------------
The command '/bin/sh -c wget -O - ${CMAKE_REPO}/v${CMAKE_VER%.*}/cmake-${CMAKE_VER}.tar.gz | tar xz &&     cd cmake-${CMAKE_VER} &&     ./bootstrap --prefix="/usr" --system-curl &&     make -j8 &&     make install' returned a non-zero code: 11
Xeon/centos-7.4/ffmpeg/CMakeFiles/build_xeon_ffmpeg_centos74.dir/build.make:57: recipe for target 'Xeon/centos-7.4/ffmpeg/CMakeFiles/build_xeon_ffmpeg_centos74' failed
make[2]: *** [Xeon/centos-7.4/ffmpeg/CMakeFiles/build_xeon_ffmpeg_centos74] Error 11
CMakeFiles/Makefile2:2261: recipe for target 'Xeon/centos-7.4/ffmpeg/CMakeFiles/build_xeon_ffmpeg_centos74.dir/all' failed
make[1]: *** [Xeon/centos-7.4/ffmpeg/CMakeFiles/build_xeon_ffmpeg_centos74.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
The command "make" exited with 2.

**Comment by deathboydmi** [comment]
@jhou5 
Yes, I saw this error and now I'm trying to fix it.
I added a zlib installation to template/build-tools.m4:3. But after that, cmake doesn't see curl. I tried to add it to the list of installable packages:
```
RUN yum install -y -q bzip2 make autoconf libtool git wget ca-certificates pkg-config gcc gcc-c++ bison flex patch epel-release yum-devel curl zlib-devel;
```
but cmake still does not see curl:
```shell
Error when bootstrapping CMake:
Problem while running initial CMake
---------------------------------------------
-- Using system-installed CURL
-- Using system-installed ZLIB
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:404 (message):
  CMAKE_USE_SYSTEM_CURL is ON but a curl is not found!
Call Stack (most recent call first):
  CMakeLists.txt:685 (CMAKE_BUILD_UTILITIES)
```

Sorry, I dont really understand "in this topic" :) So I'll be glad to any help)

**Comment by deathboydmi** [comment]
@jhou5 
I fixed all that is required, please merge my changes.

**Comment by jhou5** [comment]
Looks good to me. Thanks a lot.

**Comment by deathboydmi** [comment]
Thank you for cooperation too

**Pull request merged**
