### PR TITLE
travis: Fix ffmpeg+gst+dev builds not finding scripts

### PR DESCRIPTION
**Pull request by 1480c1**

### CODE REVIEW

**Comment by jhou5** [comment]
I'd like the changed into master first, as ffmpeg+gest+dev package build looks workable. Although there still have environment issue which may confuse others, we can fix it later.

Confuse information is shown as below: https://github.com/OpenVisualCloud/Dockerfiles/pull/95/checks 

131.36 centos-7.4/ffmpeg+gst+dev | \["CPU=Xeon buildOS=centos-7.4 imageName=dldt+ffmpeg"\] | Linux | errored | This job is allowed to fail.
-- | -- | -- | -- | --
131.37 centos-7.5/ffmpeg+gst+dev | \["CPU=Xeon buildOS=centos-7.4 imageName=dldt+ffmpeg"\] | Linux | failed | This job is allowed to fail.
131.38 centos-7.6/ffmpeg+gst+dev | \["CPU=Xeon buildOS=centos-7.4 imageName=dldt+ffmpeg"\] | Linux | failed | This job is allowed to fail.
131.39 ubuntu-16.04/ffmpeg+gst+dev | \["CPU=Xeon buildOS=centos-7.4 imageName=dldt+ffmpeg"\] | Linux | failed | This job is allowed to fail.
131.40 ubuntu-18.04/ffmpeg+gst+dev | \["CPU=Xeon buildOS=centos-7.4 imageName=dldt+ffmpeg"\] | Linux | failed | This job is allowed to fail.

**Comment by 1480c1** [comment]
I see, it's because the individual include jobs do not have an env: key and as such inherited the first one.

**Comment by jhou5** [comment]
It should works now. 👍 Thanks for quick response!

**Comment by 1480c1** [comment]
No problem

**Pull request merged**
