### PR TITLE
reduce VCAC-A images size through deleting un-useful files under /opt…

### PR DESCRIPTION
**Pull request by jhou5**
…/intel/

### CODE REVIEW

**Comment by jhou5** [comment]
only one shell under bin - setupvars.sh, it is only 8k size. I recover it.
for duplicated copy openvino issue, fixed in new code.
and remove more files. 
Would submit a new PR soon

**Comment by jhou5** [comment]
Done for the code updating

**Comment by jhou5** [comment]
Saved 480GB arelday fater the clean up. 

I checked ubuntu18.04 deb packages data, before installation, the size is: 64.2MB, after installation, the size is: 968MB. The major impact is from INSTALL_PKGS_GST , INSTALL_PKGS_VA_GST_PLUGINS, INSTALL_PKGS_OPENVINO. Would continue to see how to optimize the image size.

**Comment by jhou5** [comment]
Correct typo: Saved 480MB arelday fater the clean up.  
Below tools is really big size, do we really need them all: 
libboost-all-dev(570MB) - from INSTALL PKGS_OPENVINO, 
libglib2.0(200MB) - from INSTALL_PKGS_GST
gobject-introspection(230MB) - from INSTALL_PKGS_GST
libgtk2.0(370MB) - from INSTALL_PKGS_VA_GST_PLUGINS

**Comment by xwu2git** [comment]
That is nice.
Libboost: We don’t need the -dev packages in the final package. Instead need the corresponding runtime package. Gobject-inspect is a python package. Likely not needed. Gtk is for display only. Not needed.

**Comment by xwu2git** [comment]
Sorry. Push the wrong button.

**Comment by jhou5** [comment]
Merge the first fix first. Would continue on removing the big size pacakages found in final run-time images with another PR.

**Pull request merged**
