### PR TITLE
Add dldt+ffmpeg test

### PR DESCRIPTION
**Pull request by linxie47**

### CODE REVIEW

**Comment by jhou5** [comment]
dldt + ffmpeg still failed

**Comment by linxie47** [comment]
> dldt + ffmpeg still failed

/mnt/ffmpeg_flv_hevc.sh: line 4:     7 Segmentation fault      (core dumped) ffmpeg -f rawvideo -vcodec rawvideo -s 320x240 -r 30 -pix_fmt yuv420p -i test.yuv -c:v libsvt_hevc -f flv -y test.flv
 2/11 Test  #2: test_xeon_dldt_ffmpeg_ubuntu1804_ffmpeg_flv_hevc ...............***Failed    3.90 sec

Actually, it's a ffmpeg+svt failure, not caused by my changes. However, I appended one change to retrigger the CI and let's recheck the result this time.

**Comment by linxie47** [comment]
@jhou5 CI passed finally.

**Comment by jhou5** [comment]
Looks good!

**Pull request merged**
