### PR TITLE
fix to gst analytic

### PR DESCRIPTION
**Pull request by QuPengfei**
- fix the error with gstgva

### CODE REVIEW

**Comment by xwu2git** [comment]
It's too invasive to copy all build python packages to deployment. Let's figure out what exactly is needed and install them directly at the final package.

**Comment by dpatel257** [comment]
@xwu2git @QuPengfei What is the best way to test gstgva ?
I generally smoke test 'gst-inspect gvapython' or 'gst-inspect gvadetect' to make sure it is functioning.

**Comment by xwu2git** [comment]
@nnshah1, can you comment? What's additionally needed to make gstgva functioning? @QuPengfei copied all build python packages to the final image, which did not seem necessary.

**Comment by xwu2git** [comment]
root@43e43e8e153d:/home# cat /mnt/gst_python.sh
#!/bin/bash -e

case "$1" in
    *analytics*)
        rm -rf /home/signal
        mkdir -p /home/signal
        cat > /home/testgva.py << EOF
from gstgva import VideoFrame, util
from pathlib import Path
class testgva:
    def __init__(self):
        Path('/home/signal/__init__').touch()

    def process_frame(self, frame):
        Path('/home/signal/process_frame').touch()
        return True
EOF

        dd if=/dev/urandom bs=115200 count=30 of=/home/test.yuv # 1 seconds video
        PATH="/home:$PATH" gst-launch-1.0 -v filesrc location=/home/test.yuv ! videoparse format=i420 width=320 height=240 framerate=30 ! videoconvert ! video/x-raw,format=BGRx ! gvapython module="testgva" class="testgva" ! fakesink
        test -f /home/signal/__init__
        test -f /home/signal/process_frame
        ;;
esac
root@43e43e8e153d:/home# /mnt/gst_python.sh analytics
30+0 records in
30+0 records out
3456000 bytes (3.5 MB, 3.3 MiB) copied, 0.090674 s, 38.1 MB/s

(gst-plugin-scanner:17): GStreamer-WARNING **: 20:53:18.473: Failed to load plugin '/usr/local/lib/x86_64-linux-gnu/gstreamer-1.0/libvasot.so': libopencv_video.so.4.3: cannot open shared object file: No such file or directory

(gst-plugin-scanner:17): GLib-GObject-CRITICAL **: 20:53:18.724: g_object_class_install_property: assertion 'property_id > 0' failed

(gst-plugin-scanner:17): GStreamer-WARNING **: 20:53:18.883: Failed to load plugin '/usr/local/lib/x86_64-linux-gnu/gstreamer-1.0/libvasot.so': libopencv_video.so.4.3: cannot open shared object file: No such file or directory
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstGvaPython:gvapython0: Error creating Python callback
Additional debug info:
/home/gst-video-analytics/gst/elements/gvapython/gstgvapython.c(205): gst_gva_python_start (): /GstPipeline:pipeline0/GstGvaPython:gvapython0:
Module: testgva
 Class: testgva
 Function: process_frame
 Arg: []
Keyword Arg: {}

Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by dpatel257** [comment]
thanks @xwu2git , looking at it.

**Comment by nnshah1** [comment]
@dpatel257 I'm looking as well - let's keep in sync.

**Comment by xwu2git** [comment]
@nnshah1 told me that the folder gst-video-analytics/python/gstgva must be copied to the final image python path: such as /usr/local/lib/python36/dist-packages.

**Comment by nnshah1** [comment]
I added it into /opt/intel/dl_streamer/python - to match /opt/intel/dldt 

Also need to add numpy, where is the correct place to add numpy?

**Comment by dpatel257** [comment]
> I added it into /opt/intel/dl_streamer/python - to match /opt/intel/dldt
> 
> Also need to add numpy, where is the correct place to add numpy?

Install 'numpy' ?
This come from template/gstreamer-videoanalytics.m4. It will be the correct place

**Comment by dpatel257** [comment]
Okay, I think I have run into this before.

```
Python 3.6.8 (default, Aug  7 2019, 17:28:10)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gstgva import VideoFrame, util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/gstgva/__init__.py", line 7, in <module>
    from .region_of_interest import RegionOfInterest
  File "/usr/lib64/python3.6/gstgva/region_of_interest.py", line 15, in <module>
    from .tensor import Tensor
  File "/usr/lib64/python3.6/gstgva/tensor.py", line 12, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

This install PyGObject, but python3 stil cant find 'gi'
`yum install python36-gobject python3-devel python36-gobject-devel python36-gobject-base`

**Comment by nnshah1** [comment]
working with @dpatel257, we understand we need to add the copy:

RUN mkdir -p build/opt/intel/dl_streamer/python && \
    cp -r gst-video-analytics/python/* build/opt/intel/dl_streamer/python
RUN mkdir -p /opt/intel/dl_streamer/python && \
    cp -r gst-video-analytics/python/* /opt/intel/dl_streamer/python
ENV GST_PLUGIN_PATH=${GST_PLUGIN_PATH}:/usr/local/ifelse(index(DOCKER_IMAGE,ubuntu),-1,lib64,lib/x86_64-linux-gnu)/gstreamer-1.0)dnl
ENV PYTHONPATH=${PYTHONPATH}:/opt/intel/dl_streamer/python

Plus gst python:

# Build gstreamer python
ARG GST_PYTHON_REPO=https://gstreamer.freedesktop.org/src/gst-python/gst-python-${GST_VER}.tar.xz
RUN  wget -O - ${GST_PYTHON_REPO} | tar xJ && \
     cd gst-python-${GST_VER} && \
     ./autogen.sh \
        --prefix=/usr/local \
        --libdir=/usr/local/lib/x86_64-linux-gnu \
        --libexecdir=/usr/local/lib/x86_64-linux-gnu \
        --with-pygi-overrides-dir=/usr/lib/python3/dist-packages/gi/overrides \
        --disable-dependency-tracking \
        --disable-silent-rules \
        --with-libpython-dir="/usr/lib/x86_64-linux-gnu/" \
        PYTHON=/usr/bin/python3 && \
     make -j $(nproc) && \
     make install DESTDIR=/home/build && \
     make install

plus the export:

root@a06a9443f1d6:/home# export GI_TYPELIB_PATH=${GI_TYPELIB_PATH}:/usr/local/lib/x86_64-linux-gnu/girepository-1.0

Trying verify gvapython now -

**Comment by dpatel257** [comment]
> ```shell
> #!/bin/bash -e
> case "$1" in
>     *analytics*)
>         rm -rf /home/signal
>         mkdir -p /home/signal
>         cat > /home/testgva.py << EOF
> from gstgva import VideoFrame, util
> from pathlib import Path
> class testgva:
>     def __init__(self):
>         Path('/home/signal/__init__').touch()
> 
>     def process_frame(self, frame):
>         Path('/home/signal/process_frame').touch()
>         return True
> EOF
> 
>         dd if=/dev/urandom bs=115200 count=30 of=/home/test.yuv # 1 seconds video
>         PATH="/home:$PATH" gst-launch-1.0 -v filesrc location=/home/test.yuv ! videoparse format=i420 width=320 height=240 framerate=30 ! videoconvert ! video/x-raw,format=BGRx ! gvapython module="testgva" class="testgva" ! fakesink
>         test -f /home/signal/__init__
>         test -f /home/signal/process_frame
>         ;;
> esac
> ```

Thanks @xwu2git , I would change the smoke test and replace it with this. This tests gvapython thoroughly

**Comment by nnshah1** [comment]
I have verified with the above changes that we can basic test: 

gst-launch-1.0 videotestsrc ! videoconvert ! gvapython module=temp.py ! fakesink

However seeing a crash at the end - need to confirm / debug

**Comment by xwu2git** [comment]
I got ubuntu 1804 working. 
https://github.com/xwu2git/Dockerfiles/commit/22277467dc754eee123d9713e6c7a934266b7483
ubuntu1604 can be fixed similarly. 
But centos does not have python3-gi or python3-gst-1.0 packages.

**Comment by nnshah1** [comment]
@dpatel257 and I got centos working as well - he's checking in now

**Comment by nnshah1** [comment]
Will - debug further on the crash I am seeing - but is not seen with the smoke test - so may be specific to the pipeline I am trying

**Comment by dpatel257** [comment]
> I got ubuntu 1804 working.
> [xwu2git@2227746](https://github.com/xwu2git/Dockerfiles/commit/22277467dc754eee123d9713e6c7a934266b7483)
> ubuntu1604 can be fixed similarly.
> But centos does not have python3-gi or python3-gst-1.0 packages.

@xwu2git Awesome !!, I will take a look at those changes and consolidate into a commit here.
@nnshah1 and I were working on the same, ubuntu1604 and centos76 working. Will test c74/c75 and push.

@nnshah1 Thanks a lot for your time and help

**Comment by dpatel257** [comment]
CentOS working in build layer, execution layer, there is some weird problem with GI. Looking into it.

**Comment by xwu2git** [comment]
Thanks all.

**Comment by QuPengfei** [comment]
@dpatel257 @xwu2git 
i saw another issue: va gstreamer plugins is not installed in vcaca gst file. 
https://github.com/OpenVisualCloud/Dockerfiles/blob/master/VCAC-A/ubuntu-18.04/analytics/gst/Dockerfile#L571

**Comment by xwu2git** [comment]
@dpatel257 Looks like macro expansion is not done correctly.

**Comment by QuPengfei** [comment]
@xwu2git @dpatel257 @nnshah1 

for gstgva fix,  i do a quick check the folder gst-video-analytics/python/*, there are only the following files and no other package. so  original fix is the easy way.

root@00e2693bdfc5:/home# ls gst-video-analytics/python
gstgva
root@00e2693bdfc5:/home# ls gst-video-analytics/python/gstgva/
__init__.py  region_of_interest.py  tensor.py  util.py  video_frame.py

**Comment by nnshah1** [comment]
@QuPengfei  this is correct - I recommend putting the files in:

/opt/intel/dl_streamer/python 

And adding that to the path - as its not really a 'package'

**Comment by xwu2git** [comment]
@dpatel257 , there is 1 more potential error. see the below error messages in xeon-ubuntu1804-analytics-gst: 

(gst-plugin-scanner:17): GStreamer-WARNING **: 20:53:18.883: Failed to load plugin '/usr/local/lib/x86_64-linux-gnu/gstreamer-1.0/libvasot.so': libopencv_video.so.4.3: cannot open shared object file: No such file or directory

I wonder where the dependency libopencv_video.so.4.3 comes from? We have opencv 4.1 in our template. Who built gst with opencv 4.3?

**Comment by QuPengfei** [comment]
update the following:
    - fix with gstgva
    - fix vcaca ubuntu18.04
    - enable element gvaidentify

**Comment by dpatel257** [comment]
> @dpatel257 @xwu2git
> i saw another issue: va gstreamer plugins is not installed in vcaca gst file.
> https://github.com/OpenVisualCloud/Dockerfiles/blob/master/VCAC-A/ubuntu-18.04/analytics/gst/Dockerfile#L571

That comment is by mistake, but on 1804/VCACA images this won't be **built from source** as they are copied from openvino dl_streamer now on. I will make sure why it doesn't work though.

**Comment by dpatel257** [comment]
> @dpatel257 , there is 1 more potential error. see the below error messages in xeon-ubuntu1804-analytics-gst:
> 
> (gst-plugin-scanner:17): GStreamer-WARNING **: 20:53:18.883: Failed to load plugin '/usr/local/lib/x86_64-linux-gnu/gstreamer-1.0/libvasot.so': libopencv_video.so.4.3: cannot open shared object file: No such file or directory
> 
> I wonder where the dependency libopencv_video.so.4.3 comes from? We have opencv 4.1 in our template. Who built gst with opencv 4.3?

I have been mystified by the same, need to dig more.

**Comment by dpatel257** [comment]
> @dpatel257 , there is 1 more potential error. see the below error messages in xeon-ubuntu1804-analytics-gst:
> 
> (gst-plugin-scanner:17): GStreamer-WARNING **: 20:53:18.883: Failed to load plugin '/usr/local/lib/x86_64-linux-gnu/gstreamer-1.0/libvasot.so': libopencv_video.so.4.3: cannot open shared object file: No such file or directory
> 
> I wonder where the dependency libopencv_video.so.4.3 comes from? We have opencv 4.1 in our template. Who built gst with opencv 4.3?

@xwu2git started new issue to track them cleanly : https://github.com/OpenVisualCloud/Dockerfiles/issues/474

**Comment by dpatel257** [comment]
Created another PR to reviewing all the feedbacks : https://github.com/OpenVisualCloud/Dockerfiles/pull/475

Summary:
- fixed gstgva
- fixed gstgva for vcac-a/ubuntu1804 images
- gvaidentify - not building as per discussion in the emails

**Comment by xwu2git** [comment]
@dpatel257 , the opencv4.3 dependency comes from gstva, where there is a binary component in the repo (delivered as a zip file,) even if we compile it from source. We need to upgrade opencv to 4.3.

**Comment by jhou5** [comment]
Pushed OpenCV 4.3 to PR#475

**Comment by jhou5** [comment]
merged PR #475, close old one.

**Pull request closed without merging**
