### PR TITLE
Scripts: Use some bashisms and quote some variables to prevent globbing

### PR DESCRIPTION
**Pull request by 1480c1**

### CODE REVIEW

**Comment by 1480c1** [comment]
Actually, wait a bit before review, want to check on my laptop

**Comment by 1480c1** [comment]
Should be fine for review

**Comment by xwu2git** [comment]
Looks fine to me.

**Comment by xwu2git** [comment]
Just curious as I don't fully understand how bash treats space in variables. 
If DIR contains space, does [[ -z $DIR ]] actually work? Normally I would use [[ -z "$DIR" ]] to avoid that. 
However, sometimes it is difficult. How to do something like this: echo "$(ls "$DIR")"?

**Comment by 1480c1** [comment]
In bash `[[` is a shell keyword instead of a shell built-in, so instead of running it as a command, bash will try to parse from the beginning `[[` to the `]]` so it does not parse spaces separately in variables like `[` does. However, echo, subshells, and ls are different so they will parse spaces like normal

`touch a b; dir="a b"; ls -l $dir` produces
```bash
-rw-r--r-- 1 cddeg cddeg      0 Jan 18 23:01 a
-rw-r--r-- 1 cddeg cddeg      0 Jan 18 23:01 b
```
`rm a b; touch a\ b; dir="a b"; [[ -f $dir ]]; echo $?` produces `0`, at least for me

**Comment by jhou5** [comment]
Something wrong. All Travis CI run failed. @1480c1

**Pull request merged**
