### PR TITLE
add centos support to vcaca images

### PR DESCRIPTION
**Pull request by jhou5**

### CODE REVIEW

**Comment by jhou5** [comment]
This PR still have build issue, need a fix -
Step 68/158 : RUN source /opt/rh/devtoolset-6/enable &&     wget http://releases.llvm.org/${CLANG_VERSION}/llvm-${CLANG_VERSION}.src.tar.xz &&     wget http://releases.llvm.org/${CLANG_VERSION}/cfe-${CLANG_VERSION}.src.tar.xz &&     wget http://releases.llvm.org/${CLANG_VERSION}/clang-tools-extra-${CLANG_VERSION}.src.tar.xz &&     wget http://releases.llvm.org/${CLANG_VERSION}/compiler-rt-${CLANG_VERSION}.src.tar.xz &&     xz -d llvm-${CLANG_VERSION}.src.tar.xz &&     tar xvf llvm-${CLANG_VERSION}.src.tar &&     xz -d cfe-${CLANG_VERSION}.src.tar.xz &&     tar xvf cfe-${CLANG_VERSION}.src.tar &&     xz -d clang-tools-extra-${CLANG_VERSION}.src.tar.xz &&     tar xvf clang-tools-extra-${CLANG_VERSION}.src.tar &&     xz -d compiler-rt-${CLANG_VERSION}.src.tar.xz &&     tar xvf compiler-rt-${CLANG_VERSION}.src.tar &&     cd llvm-${CLANG_VERSION}.src &&     mv ../cfe-${CLANG_VERSION}.src tools/clang &&     mv ../clang-tools-extra-${CLANG_VERSION}.src tools/clang/extra &&     mv ../compiler-rt-${CLANG_VERSION}.src projects/compiler-rt &&     mkdir build &&     cd build &&     cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=On .. &&     make -j$(nproc)  &&     make install
 ---> Running in cbc4486c3b63
/bin/sh: /opt/rh/devtoolset-6/enable: No such file or directory

**Comment by dpatel257** [comment]
This

> This PR still have build issue, need a fix -
> Step 68/158 : RUN source /opt/rh/devtoolset-6/enable && wget [http://releases.llvm.org/${CLANG_VERSION}/llvm-${CLANG_VERSION}.src.tar.xz](http://releases.llvm.org/$%7BCLANG_VERSION%7D/llvm-$%7BCLANG_VERSION%7D.src.tar.xz) && wget [http://releases.llvm.org/${CLANG_VERSION}/cfe-${CLANG_VERSION}.src.tar.xz](http://releases.llvm.org/$%7BCLANG_VERSION%7D/cfe-$%7BCLANG_VERSION%7D.src.tar.xz) && wget [http://releases.llvm.org/${CLANG_VERSION}/clang-tools-extra-${CLANG_VERSION}.src.tar.xz](http://releases.llvm.org/$%7BCLANG_VERSION%7D/clang-tools-extra-$%7BCLANG_VERSION%7D.src.tar.xz) && wget [http://releases.llvm.org/${CLANG_VERSION}/compiler-rt-${CLANG_VERSION}.src.tar.xz](http://releases.llvm.org/$%7BCLANG_VERSION%7D/compiler-rt-$%7BCLANG_VERSION%7D.src.tar.xz) && xz -d llvm-${CLANG_VERSION}.src.tar.xz && tar xvf llvm-${CLANG_VERSION}.src.tar && xz -d cfe-${CLANG_VERSION}.src.tar.xz && tar xvf cfe-${CLANG_VERSION}.src.tar && xz -d clang-tools-extra-${CLANG_VERSION}.src.tar.xz && tar xvf clang-tools-extra-${CLANG_VERSION}.src.tar && xz -d compiler-rt-${CLANG_VERSION}.src.tar.xz && tar xvf compiler-rt-${CLANG_VERSION}.src.tar && cd llvm-${CLANG_VERSION}.src && mv ../cfe-${CLANG_VERSION}.src tools/clang && mv ../clang-tools-extra-${CLANG_VERSION}.src tools/clang/extra && mv ../compiler-rt-${CLANG_VERSION}.src projects/compiler-rt && mkdir build && cd build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=On .. && make -j$(nproc) && make install
> ---> Running in cbc4486c3b63
> /bin/sh: /opt/rh/devtoolset-6/enable: No such file or directory

@jhou5  Which OS did you see this on ? 74 OR 76 ?

**Comment by jhou5** [comment]
centos7.6

**Comment by dpatel257** [comment]
Fixed. Try now. It was missing a yum package. Surprisingly we didnt run into this issue before because the package was already installed from other templates, but good bug you found.

**Comment by jhou5** [comment]
It works. Thanks! @dpatel257

**Pull request closed without merging**
