### PR TITLE
Enable Video Analytic Gstreamer Plugins on Xeon and XeonE3

### PR DESCRIPTION
**Pull request by fkhoshne**

### CODE REVIEW

**Comment by jhou5** [comment]
Seen from the code, the pull request are for 2 PRs:
1. Need Gstreamer inference engine plugins #21
2. Request to DLDT MO in the dev pkg #24

Am I right?

**Comment by fkhoshne** [comment]
> Seen from the code, the pull request are for 2 PRs:
> 
> 1. Need Gstreamer inference engine plugins #21
> 2. Request to DLDT MO in the dev pkg #24
> 
> Am I right?

Yes. It includes the PR for the gstreamer inference engine plugins and the PR for DLDT MO in the dev pkg. I've put the MO code inside the dldt-ie.m4 template (since IE and MO are from the same repo, it makes more sense to me that they share the same template instead of a dldt-ie and dldt-mo template). With that said, the dldt-ie.m4 should maybe be renamed to dldt.m4

**Comment by dpatel257** [comment]
ffmpeg_dldt_gst_dev package for centos75 with following error. related to how dldt is configured:

Step 126/126 : RUN cd /home/FFmpeg &&     ./configure --prefix="/usr" --libdir=/usr/lib64 --extra-libs="-lpthread -lm" --enable-shared --enable-gpl --enable-¦·······························
libass --enable-libfreetype  --enable-openssl --enable-nonfree --disable-vaapi --disable-hwaccels  --enable-libfdk-aac --enable-libmp3lame --enable-libopus -¦·······························
-enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libaom --enable-libsvthevc --enable-libsvtav1 --enable-libinference_engine  &&  make -j8 &&     make install DESTDIR="/home/build"
 ---> Running in 14c91260b187
ERROR: dldt not found using pkg-config
                                                                                                                         
If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help solve the problem.

The command '/bin/sh -c cd /home/FFmpeg &&     ./configure --prefix="/usr" --libdir=/usr/lib64 --extra-libs="-lpthread -lm" --enable-shared --enable-gpl --enable-libass --enable-libfreetype  --enable-openssl --enable-nonfree --disable-vaapi --disable-hwaccels  --enable-libfdk-aac --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libaom --enable-libsvthevc --enable-libsvtav1 --enable-libinference_engine &&     make -j8 &&     make install DESTDIR="/home/build"' returned a non-zero code: 1

Xeon/centos-7.5/ffmpeg+gst+dev/CMakeFiles/build_xeon_ffmpeg_gst_devel_centos75.dir/build.make:57: recipe for target 'Xeon/centos-7.5/ffmpeg+gst+dev/CMakeFiles/build_xeon_ffmpeg_gst_devel_centos75' failed
make[2]: *** [Xeon/centos-7.5/ffmpeg+gst+dev/CMakeFiles/build_xeon_ffmpeg_gst_devel_centos75] Error 1
CMakeFiles/Makefile2:2517: recipe for target 'Xeon/centos-7.5/ffmpeg+gst+dev/CMakeFiles/build_xeon_ffmpeg_gst_devel_centos75.dir/all' failed
make[1]: *** [Xeon/centos-7.5/ffmpeg+gst+dev/CMakeFiles/build_xeon_ffmpeg_gst_devel_centos75.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dpatel257** [comment]
All tested passed. Will merge

**Pull request merged**
