### PR TITLE
Enable SVT AV1 ffmpeg plugin

### PR DESCRIPTION
**Pull request by jsunintel**

### CODE REVIEW

**Comment by jsunintel** [comment]
Not ready to add any SVT AV1 tests due to https://github.com/OpenVisualCloud/SVT-AV1/issues/119.

**Comment by dpatel257** [comment]
Build works fine. As this is a new plugin, a test for it would be needed.

Refer to: https://github.com/OpenVisualCloud/Dockerfiles/blob/master/test/ffmpeg_svt_hevc.sh

**Comment by mediamedia** [comment]
@jsunintel, pls. add test for this new plugin.

**Comment by jsunintel** [comment]
> Not ready to add any SVT AV1 tests due to [OpenVisualCloud/SVT-AV1#119](https://github.com/OpenVisualCloud/SVT-AV1/issues/119).

Check the above message.
I already had had the tests ready. I have been working on solving the confliction between AOM and SVT AV1 libs, and will submit tests as soon as it's solved.

**Comment by jsunintel** [comment]
Tests added and verified. Ready for merging.

**Comment by jsunintel** [comment]
@dpatel257 @jhou5
I checked but fount the failed checks were like:
"The job exceeded the maximum time limit for jobs, and has been terminated."
Not my patch's fault.

**Comment by jhou5** [comment]
@jsunintel, no worry, you can ignore all builds with "!", it is caused by build time out. The result shows you have passed build. We'll further investigate how to improve build performance. Thanks!

**Comment by jsunintel** [comment]
3 days passed and this is still not merged. Is there any issue blocking it?

**Comment by dpatel257** [comment]
One of the hooks for SVT-AV1 patch was failing last checked. Need to double check.

**Comment by dpatel257** [comment]
Error on my local build:

 ---> c61f5d395fe0
Step 93/94 : RUN cd /home/FFmpeg;     patch -p1 < ../SVT-AV1/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch;
 ---> Running in 6da539770fdb
patching file configure
Hunk #3 succeeded at 3129 (offset -1 lines).
Hunk #4 FAILED at 6142.
1 out of 4 hunks FAILED -- saving rejects to file configure.rej
patching file libavcodec/Makefile
patching file libavcodec/allcodecs.c
patching file libavcodec/libsvt_av1.c
The command '/bin/sh -c cd /home/FFmpeg;     patch -p1 < ../SVT-AV1/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch;' returned a non-zero code: 1
XeonE3/ubuntu-16.04/ffmpeg+gst+dev/CMakeFiles/build_xeone3_ffmpeg_gst_devel_ubuntu1604.dir/build.make:57: recipe for target 'XeonE3/ubuntu-16.04/ffmpeg+gst+dev/CMakeFiles/build_xeone3_ffmpeg_gst_devel_ubuntu1604' failed
make[2]: *** [XeonE3/ubuntu-16.04/ffmpeg+gst+dev/CMakeFiles/build_xeone3_ffmpeg_gst_devel_ubuntu1604] Error 1
CMakeFiles/Makefile2:5837: recipe for target 'XeonE3/ubuntu-16.04/ffmpeg+gst+dev/CMakeFiles/build_xeone3_ffmpeg_gst_devel_ubuntu1604.dir/all' failed
make[1]: *** [XeonE3/ubuntu-16.04/ffmpeg+gst+dev/CMakeFiles/build_xeone3_ffmpeg_gst_devel_ubuntu1604.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jsunintel** [comment]
There is a recent SVT-AV1 lib api changes patch merged. I just rebased the plugin patch and am asking for its merging. After it's merged, I will make the corresponding change in Dockerfiles.

**Comment by dpatel257** [comment]
Are we waiting on '134ab775896091aaab9f17e3680a32d28b434cdf' to be merged in SVT-AV1 repo ? If yes, we would wait on this before merging

**Comment by jsunintel** [comment]
> 
> 
> Are we waiting on '134ab775896091aaab9f17e3680a32d28b434cdf' to be merged in SVT-AV1 repo ? If yes, we would wait on this before merging

That one is merged. We are waiting for the below patch's merging.

https://github.com/OpenVisualCloud/SVT-AV1/pull/173/commits/449bca55514a5a8a259c1d21e8e95afa3ad09fa6

**Comment by jsunintel** [comment]
Finished the code update base don SVT AV1 API changes. All tests passed. Please review and merge it if no issue.

Test project /work/Dockerfiles/build/Xeon/centos-7.6/ffmpeg
      Start  1: test_xeon_ffmpeg_centos76_ffmpeg_1dns
 1/10 Test  #1: test_xeon_ffmpeg_centos76_ffmpeg_1dns .......   Passed    2.16 sec
      Start  2: test_xeon_ffmpeg_centos76_ffmpeg_flv_hevc
 2/10 Test  #2: test_xeon_ffmpeg_centos76_ffmpeg_flv_hevc ...   Passed    2.13 sec
      Start  3: test_xeon_ffmpeg_centos76_ffmpeg_ivf_av1
 3/10 Test  #3: test_xeon_ffmpeg_centos76_ffmpeg_ivf_av1 ....   Passed    1.98 sec
      Start  4: test_xeon_ffmpeg_centos76_ffmpeg_qsv
 4/10 Test  #4: test_xeon_ffmpeg_centos76_ffmpeg_qsv ........   Passed    1.24 sec
      Start  5: test_xeon_ffmpeg_centos76_ffmpeg_svt_av1
 5/10 Test  #5: test_xeon_ffmpeg_centos76_ffmpeg_svt_av1 ....   Passed    2.03 sec
      Start  6: test_xeon_ffmpeg_centos76_ffmpeg_svt_hevc
 6/10 Test  #6: test_xeon_ffmpeg_centos76_ffmpeg_svt_hevc ...   Passed    2.12 sec
      Start  7: test_xeon_ffmpeg_centos76_ffmpeg_vaapi
 7/10 Test  #7: test_xeon_ffmpeg_centos76_ffmpeg_vaapi ......   Passed    1.17 sec
      Start  8: test_xeon_ffmpeg_centos76_ffmpeg_vpx
 8/10 Test  #8: test_xeon_ffmpeg_centos76_ffmpeg_vpx ........   Passed    6.70 sec
      Start  9: test_xeon_ffmpeg_centos76_ffmpeg_x264
 9/10 Test  #9: test_xeon_ffmpeg_centos76_ffmpeg_x264 .......   Passed    5.23 sec
      Start 10: test_xeon_ffmpeg_centos76_ffmpeg_x265
10/10 Test #10: test_xeon_ffmpeg_centos76_ffmpeg_x265 .......   Passed   14.45 sec

@dpatel257 @jhou5

**Comment by jsunintel** [comment]
Another PR was just merged and caused confliction, rebased the patch again...
Hope this patch becomes the top of the pending patches stack now.

@dpatel257 @jhou5

**Pull request merged**
