### PR TITLE
Update DLDT to R2

### PR DESCRIPTION
**Pull request by fkhoshne**
Updating DLDT template to R2 release
Also updating GST VA Plugins to v0.5 to coincide with R2 release

### CODE REVIEW

**Comment by jhou5** [comment]
ffmpeg analytics image build failed. pls. kindly double check. @fkhoshne

**Comment by fkhoshne** [comment]
> ffmpeg analytics image build failed. pls. kindly double check. @fkhoshne

Will look into it, the test for gst analytics on CentOS also fails. Currently looking into that one.

**Comment by linxie47** [comment]
@fkhoshne 
Please amend the patch from the link as below to your banch to fix the build issue for ffmpeg analytics.

https://gist.github.com/linxie47/91b223a85cf42293e1e73722f0639557#file-0001-fix-c-api-build-issue-patch

Thanks!
-Lin

**Comment by jhou5** [comment]
@fkhoshne are you still working on this?

**Comment by fkhoshne** [comment]
> @fkhoshne are you still working on this?

I am, I need to make a few more changes to resolve the issues the CI is running into but I know what they are and will implement them in the next couple of days.

**Comment by jhou5** [comment]
@fkhoshne any update?

**Comment by jhou5** [comment]
update to DLDT R3 instead, close this PR.

**Pull request closed without merging**
