### PR TITLE
upgrade svt-av1 to v0.8.4

### PR DESCRIPTION
**Pull request by jhou5**

### CODE REVIEW

**Comment by jhou5** [comment]
@TangZhiZhen CDN patch doesn't work for SVT AV1 v0.8.4 release. Can you pls. help a fix?

Pls. refer to the test log here:
https://travis-ci.com/github/OpenVisualCloud/Dockerfiles/jobs/355530793

**Comment by 1480c1** [comment]
I do not think `0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch` exists anymore in the master branch, it was removed when making the patch atomic, thus rendered unnecessary

https://github.com/VCDP/CDN/blob/master/SVT-AV1_patches/0001-Add-the-thread-count-parameter-support.patch

this patch might also need to be rebased because of the recent changes to unpin token

**Comment by jhou5** [comment]
Thanks @1480c1 . 
1. Remove https://github.com/VCDP/CDN/blob/master/SVT-AV1_patches/0001-Add-the-thread-count-parameter-support.patch till it is ready;
2. Change to use 0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch, then 0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch is failed to apply for. 
Need a new SVT VP9 patch.

**Comment by jhou5** [comment]
Upgrade svt vp9 to v0.2.1, to fix svt vp9 ffmpeg plugin failure.

**Pull request merged**
