### PR TITLE
adding the usage segment as part of the image name and a prefix: openvisualcloud.

### PR DESCRIPTION
**Pull request by jhou5**
#84

### CODE REVIEW

**Comment by 1480c1** [comment]
You can do `git rebase upstream/master -i` (if OVC is set up as upstream remote) and fixup the typos or reword etc so that they do not pollute the history

**Comment by jhou5** [comment]
@tszumski, how do you think if we renamed xeon-centos74-graphics-ospray-mpi?
-----------------------------------------------------------------------------------------------------------------
xwu2git left a comment
extra - in xeon-centos74--graphics-ospray-oiio-mpi.
BTW, does oiio here mean anything significant? If not, it's better not to make extra long image names.
-----------------------------------------------------------------------------------------------------------------

**Comment by jhou5** [comment]
> You can do `git rebase upstream/master -i` (if OVC is set up as upstream remote) and fixup the typos or reword etc so that they do not pollute the history

good idea, would use it and thanks!

**Comment by jhou5** [comment]
> centos-7x image names missed a "-".

fixed

**Comment by jhou5** [comment]
> Prefix may be defined in script/build.sh, instead of individual image build.sh.
> You can also use PREFIX=${PREFIX:-openvisualcloud} to allow environment overwrite.

This is really good idea. I like it.

**Comment by jhou5** [comment]
@xwu2git  Except long image name: xeon-centos74--graphics-ospray-oiio-mpi , all feedback have been included into the latest pull request. And it looks CI test passed, too.

Kindly let me know if you have more feedback.

**Comment by tszumski** [comment]
@jhou5 To my mind oiio is not necessary and name could be changed to xeon-centos74-graphics-ospray-mpi

**Comment by jhou5** [comment]
@tszumski , thanks for the confirmation. I have changed the code accordingly.

**Pull request merged**
