### PR TITLE
more robust env handling

### PR DESCRIPTION
**Pull request by xwu2git**

### CODE REVIEW

**Comment by 1480c1** [comment]
@xwu2git, can I ask what the intention of adding `cut -f1 -d=` to the subshell is?
Running `env | cut -f1 -d= | sed 's/^/--build-arg /'` produces
```bash
...
--build-arg PWD
--build-arg LOGNAME
--build-arg XDG_SESSION_TYPE
--build-arg MANPATH
...
```
while running without cut produces
```bash
...
--build-arg PWD=/code/Dockerfiles
--build-arg LOGNAME=ccom1
--build-arg XDG_SESSION_TYPE=tty
...
```

**Comment by xwu2git** [comment]
On some user's system, there are environmental variables like the following:

DOCKER_BUILD_ARGS="http_proxy=.... https_proxy=...."

This will result in passing in the wrong args.

**Comment by 1480c1** [comment]
However, running `cut -f1 -d=` will cut and only get the variable name (`_proxy`, `_REPO`, `_VER`) and discard the variable value, is that the intended output?

```bash
--build-arg _proxy --build-arg _REPO build-arg _VER
```

**Comment by 1480c1** [comment]
Rather, I guess it would be better to ask what's the intention of the `$(env | grep -E '_(proxy|REPO|VER)$' | sed 's/^/--build-arg /')`? Looking at it, it seems like you are trying to unset variables ending in `_proxy`, `_REPO`, and `_VER`?

**Comment by jhou5** [comment]
it is acutally enough. Refer to this: https://docs.docker.com/engine/reference/commandline/build/

You will find below guide:
You may also use the --build-arg flag without a value, in which case the value from the local environment will be propagated into the Docker container being built:

$ export HTTP_PROXY=http://10.20.30.2:1234
$ docker build --build-arg HTTP_PROXY .

**Comment by 1480c1** [comment]
I see, thank you for the docs, I assumed it was similar to bash when setting local variables would cause the localed variable to not have a value

**Comment by xwu2git** [comment]
Yes, docker build will pass the actual env values.

**Pull request merged**
