### PR TITLE
consume DL streamer for affected images

### PR DESCRIPTION
**Pull request by dpatel257**

### CODE REVIEW

**Comment by dpatel257** [comment]
@jhou5 Just fixed ubuntu1804 vcaca image, can you try the test now ?

**Comment by jhou5** [comment]
Thanks for the quick fix. Trying...

**Comment by xwu2git** [comment]
For VCAC-A, we need to make sure the gst-vaapi patch is there before we can consider using it.

**Comment by jhou5** [comment]
it works now. Thanks for the quick fix.

**Comment by jhou5** [comment]
@xwu2git do you mean this patch: ARG GST_PLUGIN_VAAPI_PATCH_BRANCH=preview/python_api-yolov3_support? it is patched in "gstremaer vaapi plugin" instead of "gstreamer va plugins"

**Comment by dpatel257** [comment]
> @xwu2git do you mean this patch: ARG GST_PLUGIN_VAAPI_PATCH_BRANCH=preview/python_api-yolov3_support? it is patched in "gstremaer vaapi plugin" instead of "gstreamer va plugins"

Oops, maybe not the best place to put it. Put it there because it takes care of vaapi features.
@xwu2git would you comment on it?

**Comment by dpatel257** [comment]
Regardless of where it resides, I think the plan is to consume it from vcaca/ubuntu1804/analytics/dev in SMTC (according to this https://github.com/OpenVisualCloud/Smart-City-Sample/blob/master/analytics/common/VCAC-A/gst/Dockerfile.1.txt), which is in place.

**Comment by xwu2git** [comment]
gst-vaapi.m4 is the right place to include the patch.

**Comment by xwu2git** [comment]
Please pulled the patch from the 2020.2 release branch: https://github.com/opencv/gst-video-analytics/tree/v1.0.0/patches/gstreamer-vaapi

**Comment by dpatel257** [comment]
> Please pull the patch from the 2020.2 release branch: https://github.com/opencv/gst-video-analytics/tree/v1.0.0/patches/gstreamer-vaapi

Yes, sure

**Comment by jhou5** [comment]
@dpatel257 
VCAC-A dev & gst images pass ctest, but ffmpeg image hang -
* ctest -R  test_vcaca_analytics_ffmpeg_ubuntu1804_dldt_ffmpeg_video_analytics_vcaa
* ctest -R  test_vcaca_analytics_ffmpeg_ubuntu1604_dldt_ffmpeg_video_analytics_vcaa

It looks DL_streamer change missed from ffmpeg image

**Comment by dpatel257** [comment]
Fixed hddldaemon , tested it is functionong by running vcaa based ffmpeg/gst tests.



> Please pull the patch from the 2020.2 release branch: https://github.com/opencv/gst-video-analytics/tree/v1.0.0/patches/gstreamer-vaapi

Done

**Comment by jhou5** [comment]
Finally, all test passed on VCAC-A images. Thanks for the quick fix.

**Pull request merged**
